version: '3.8'

services:
  postgres:
    container_name: postgresTradeBot
    image: postgres
    environment:
      POSTGRES_DB: tradebot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
